# Generated by Django 2.2.4 on 2020-03-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True, unique=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('rid', models.IntegerField()),
                ('mobile', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64)),
                ('ut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserType')),
            ],
        ),
    ]
