# Generated by Django 2.2.4 on 2020-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
