# Generated by Django 2.2.4 on 2020-03-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_menulist_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='app01.MenuList'),
        ),
    ]
