# Generated by Django 2.2.4 on 2020-03-26 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200325_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mg_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='app01.MenuList'),
        ),
    ]
